### Добавить продукт в корзину
GET http://localhost:8080/order/add?id=12

### Добавить продукт в корзину 2
GET http://localhost:8080/store/order/add?id=1

### Получить список продуктов в корзине
GET http://localhost:8080/store/order/get
